export default {
  JSON: {
    totalResultsCount: 82,
    geonames: [
      {
        adminCode1: "21",
        lng: "15.97798",
        geonameId: 3186886,
        toponymName: "Zagreb",
        countryId: "3202326",
        fcl: "P",
        population: 698966,
        countryCode: "HR",
        name: "Zagreb",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "21",
        },
        countryName: "Hrvatska",
        fcodeName: "capital of a political entity",
        adminName1: "Grad Zagreb",
        lat: "45.81444",
        fcode: "PPLC",
      },
      {
        adminCode1: "15",
        lng: "16.43915",
        geonameId: 3190261,
        toponymName: "Split",
        countryId: "3202326",
        fcl: "P",
        population: 176314,
        countryCode: "HR",
        name: "Split",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "17",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Splitsko-Dalmatinska",
        lat: "43.50891",
        fcode: "PPLA",
      },
      {
        adminCode1: "12",
        lng: "14.44241",
        geonameId: 3191648,
        toponymName: "Rijeka",
        countryId: "3202326",
        fcl: "P",
        population: 141172,
        countryCode: "HR",
        name: "Rijeka",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "08",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Primorsko-Goranska",
        lat: "45.32673",
        fcode: "PPLA",
      },
      {
        adminCode1: "10",
        lng: "18.69389",
        geonameId: 3193935,
        toponymName: "Osijek",
        countryId: "3202326",
        fcl: "P",
        population: 88140,
        countryCode: "HR",
        name: "Osijek",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "14",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Osječko-Baranjska",
        lat: "45.55111",
        fcode: "PPLA",
      },
      {
        adminCode1: "02",
        lng: "18.01556",
        geonameId: 3190586,
        toponymName: "Slavonski Brod",
        countryId: "3202326",
        fcl: "P",
        population: 60742,
        countryCode: "HR",
        name: "Slavonski Brod",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "12",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Brodsko-Posavska",
        lat: "45.16028",
        fcode: "PPLA",
      },
      {
        adminCode1: "19",
        lng: "15.22514",
        geonameId: 3186952,
        toponymName: "Zadar",
        countryId: "3202326",
        fcl: "P",
        population: 71258,
        countryCode: "HR",
        name: "Zadar",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "13",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Zadarska",
        lat: "44.11578",
        fcode: "PPLA",
      },
      {
        adminCode1: "05",
        lng: "15.55",
        geonameId: 3345300,
        toponymName: "Karlovac",
        countryId: "3202326",
        fcl: "P",
        population: 46833,
        countryCode: "HR",
        name: "Karlovac",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "04",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Karlovačka",
        lat: "45.49167",
        fcode: "PPLA",
      },
      {
        adminCode1: "16",
        lng: "16.33778",
        geonameId: 3188383,
        toponymName: "Varaždin",
        countryId: "3202326",
        fcl: "P",
        population: 41808,
        countryCode: "HR",
        name: "Varaždin",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "05",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Varaždinska",
        lat: "46.30444",
        fcode: "PPLA",
      },
      {
        adminCode1: "04",
        lng: "13.84806",
        geonameId: 3192224,
        toponymName: "Pula",
        countryId: "3202326",
        fcl: "P",
        population: 59078,
        countryCode: "HR",
        name: "Pula",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "18",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Istarska",
        lat: "44.86833",
        fcode: "PPLA2",
      },
      {
        adminCode1: "21",
        lng: "16.11639",
        geonameId: 3190966,
        toponymName: "Sesvete",
        countryId: "3202326",
        fcl: "P",
        population: 52411,
        countryCode: "HR",
        name: "Sesvete",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "21",
        },
        countryName: "Hrvatska",
        fcodeName: "populated place",
        adminName1: "Grad Zagreb",
        lat: "45.83111",
        fcode: "PPL",
      },
      {
        adminCode1: "03",
        lng: "18.10909",
        geonameId: 3201047,
        toponymName: "Dubrovnik",
        countryId: "3202326",
        fcl: "P",
        population: 28428,
        countryCode: "HR",
        name: "Dubrovnik",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "19",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Dubrovačko-Neretvanska",
        lat: "42.64125",
        fcode: "PPLA",
      },
      {
        adminCode1: "06",
        lng: "16.8275",
        geonameId: 3197728,
        toponymName: "Koprivnica",
        countryId: "3202326",
        fcl: "P",
        population: 25579,
        countryCode: "HR",
        name: "Koprivnica",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "06",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Koprivničko-Križevačka",
        lat: "46.16278",
        fcode: "PPLA",
      },
      {
        adminCode1: "11",
        lng: "17.68528",
        geonameId: 3190589,
        toponymName: "Požega",
        countryId: "3202326",
        fcl: "P",
        population: 21153,
        countryCode: "HR",
        name: "Požega",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "11",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Požeško-Slavonska",
        lat: "45.34028",
        fcode: "PPLA",
      },
      {
        adminCode1: "14",
        lng: "16.37833",
        geonameId: 3190813,
        toponymName: "Sisak",
        countryId: "3202326",
        fcl: "P",
        population: 35748,
        countryCode: "HR",
        name: "Sisak",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "03",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Sisačko-Moslavačka",
        lat: "45.46611",
        fcode: "PPLA",
      },
      {
        adminCode1: "13",
        lng: "15.8942",
        geonameId: 3190941,
        toponymName: "Šibenik",
        countryId: "3202326",
        fcl: "P",
        population: 37112,
        countryCode: "HR",
        name: "Šibenik",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "15",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Šibensko-Kninska",
        lat: "43.73429",
        fcode: "PPLA",
      },
      {
        adminCode1: "18",
        lng: "19.00225",
        geonameId: 3187047,
        toponymName: "Vukovar",
        countryId: "3202326",
        fcl: "P",
        population: 29584,
        countryCode: "HR",
        name: "Vukovar",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "16",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Vukovarsko-Srijemska",
        lat: "45.35161",
        fcode: "PPLA",
      },
      {
        adminCode1: "09",
        lng: "16.43389",
        geonameId: 3202888,
        toponymName: "Čakovec",
        countryId: "3202326",
        fcl: "P",
        population: 15867,
        countryCode: "HR",
        name: "Čakovec",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "20",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Međimurska",
        lat: "46.38444",
        fcode: "PPLA",
      },
      {
        adminCode1: "01",
        lng: "16.84889",
        geonameId: 3203982,
        toponymName: "Bjelovar",
        countryId: "3202326",
        fcl: "P",
        population: 28275,
        countryCode: "HR",
        name: "Bjelovar",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "07",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Bjelovarsko-Bilogorska",
        lat: "45.89861",
        fcode: "PPLA",
      },
      {
        adminCode1: "04",
        lng: "13.93667",
        geonameId: 3193561,
        toponymName: "Pazin",
        countryId: "3202326",
        fcl: "P",
        population: 5010,
        countryCode: "HR",
        name: "Pazin",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "18",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Istarska",
        lat: "45.24028",
        fcode: "PPLA",
      },
      {
        adminCode1: "08",
        lng: "15.37472",
        geonameId: 3199873,
        toponymName: "Gospić",
        countryId: "3202326",
        fcl: "P",
        population: 6118,
        countryCode: "HR",
        name: "Gospić",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "09",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Ličko-Senjska",
        lat: "44.54611",
        fcode: "PPLA",
      },
      {
        adminCode1: "15",
        lng: "16.49314",
        geonameId: 3190359,
        toponymName: "Solin",
        countryId: "3202326",
        fcl: "P",
        population: 20212,
        countryCode: "HR",
        name: "Solin",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "17",
        },
        countryName: "Hrvatska",
        fcodeName: "populated place",
        adminName1: "Splitsko-Dalmatinska",
        lat: "43.5432",
        fcode: "PPL",
      },
      {
        adminCode1: "17",
        lng: "17.38389",
        geonameId: 3187694,
        toponymName: "Virovitica",
        countryId: "3202326",
        fcl: "P",
        population: 15665,
        countryCode: "HR",
        name: "Virovitica",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "10",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Virovitičko-Podravska",
        lat: "45.83194",
        fcode: "PPLA",
      },
      {
        adminCode1: "07",
        lng: "15.87889",
        geonameId: 3197369,
        toponymName: "Krapina",
        countryId: "3202326",
        fcl: "P",
        population: 4725,
        countryCode: "HR",
        name: "Krapina",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "02",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a first-order administrative division",
        adminName1: "Krapinsko-Zagorska",
        lat: "46.16083",
        fcode: "PPLA",
      },
      {
        adminCode1: "15",
        lng: "16.25167",
        geonameId: 3188763,
        toponymName: "Trogir",
        countryId: "3202326",
        fcl: "P",
        population: 10960,
        countryCode: "HR",
        name: "Trogir",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "17",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Splitsko-Dalmatinska",
        lat: "43.5125",
        fcode: "PPLA2",
      },
      {
        adminCode1: "04",
        lng: "13.63457",
        geonameId: 3191518,
        toponymName: "Rovinj",
        countryId: "3202326",
        fcl: "P",
        population: 13533,
        countryCode: "HR",
        name: "Rovinj",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "18",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Istarska",
        lat: "45.08268",
        fcode: "PPLA2",
      },
      {
        adminCode1: "03",
        lng: "17.64833",
        geonameId: 3195222,
        toponymName: "Metković",
        countryId: "3202326",
        fcl: "P",
        population: 13941,
        countryCode: "HR",
        name: "Metković",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "19",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Dubrovačko-Neretvanska",
        lat: "43.05417",
        fcode: "PPLA2",
      },
      {
        adminCode1: "15",
        lng: "17.01778",
        geonameId: 3195890,
        toponymName: "Makarska",
        countryId: "3202326",
        fcl: "P",
        population: 13446,
        countryCode: "HR",
        name: "Makarska",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "17",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Splitsko-Dalmatinska",
        lat: "43.29694",
        fcode: "PPLA2",
      },
      {
        adminCode1: "13",
        lng: "16.19662",
        geonameId: 3197986,
        toponymName: "Knin",
        countryId: "3202326",
        fcl: "P",
        population: 11182,
        countryCode: "HR",
        name: "Knin",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "15",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Šibensko-Kninska",
        lat: "44.04063",
        fcode: "PPLA2",
      },
      {
        adminCode1: "20",
        lng: "16.07556",
        geonameId: 3188244,
        toponymName: "Velika Gorica",
        countryId: "3202326",
        fcl: "P",
        population: 35072,
        countryCode: "HR",
        name: "Velika Gorica",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "01",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Zagrebačka",
        lat: "45.7125",
        fcode: "PPLA2",
      },
      {
        adminCode1: "15",
        lng: "16.63944",
        geonameId: 3190865,
        toponymName: "Sinj",
        countryId: "3202326",
        fcl: "P",
        population: 11524,
        countryCode: "HR",
        name: "Sinj",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "17",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Splitsko-Dalmatinska",
        lat: "43.70361",
        fcode: "PPLA2",
      },
      {
        adminCode1: "04",
        lng: "13.59511",
        geonameId: 3192699,
        toponymName: "Poreč",
        countryId: "3202326",
        fcl: "P",
        population: 10499,
        countryCode: "HR",
        name: "Poreč",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "18",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Istarska",
        lat: "45.22567",
        fcode: "PPLA2",
      },
      {
        adminCode1: "15",
        lng: "16.55013",
        geonameId: 3192910,
        toponymName: "Podstrana",
        countryId: "3202326",
        fcl: "P",
        population: 9129,
        countryCode: "HR",
        name: "Podstrana",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "17",
        },
        countryName: "Hrvatska",
        fcodeName: "populated place",
        adminName1: "Splitsko-Dalmatinska",
        lat: "43.48668",
        fcode: "PPL",
      },
      {
        adminCode1: "20",
        lng: "15.80778",
        geonameId: 3186781,
        toponymName: "Zaprešić",
        countryId: "3202326",
        fcl: "P",
        population: 19664,
        countryCode: "HR",
        name: "Zaprešić",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "01",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Zagrebačka",
        lat: "45.85639",
        fcode: "PPLA2",
      },
      {
        adminCode1: "18",
        lng: "18.80472",
        geonameId: 3187719,
        toponymName: "Vinkovci",
        countryId: "3202326",
        fcl: "P",
        population: 33314,
        countryCode: "HR",
        name: "Vinkovci",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "16",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Vukovarsko-Srijemska",
        lat: "45.28833",
        fcode: "PPLA2",
      },
      {
        adminCode1: "10",
        lng: "18.41056",
        geonameId: 3202220,
        toponymName: "Đakovo",
        countryId: "3202326",
        fcl: "P",
        population: 19491,
        countryCode: "HR",
        name: "Đakovo",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "14",
        },
        countryName: "Hrvatska",
        fcodeName: "populated place",
        adminName1: "Osječko-Baranjska",
        lat: "45.30833",
        fcode: "PPL",
      },
      {
        adminCode1: "20",
        lng: "15.64861",
        geonameId: 3198799,
        toponymName: "Jastrebarsko",
        countryId: "3202326",
        fcl: "P",
        population: 5445,
        countryCode: "HR",
        name: "Jastrebarsko",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "01",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Zagrebačka",
        lat: "45.66833",
        fcode: "PPLA2",
      },
      {
        adminCode1: "14",
        lng: "16.78194",
        geonameId: 3196864,
        toponymName: "Kutina",
        countryId: "3202326",
        fcl: "P",
        population: 14886,
        countryCode: "HR",
        name: "Kutina",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "03",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Sisačko-Moslavačka",
        lat: "45.475",
        fcode: "PPLA2",
      },
      {
        adminCode1: "06",
        lng: "16.5425",
        geonameId: 3197230,
        toponymName: "Križevci",
        countryId: "3202326",
        fcl: "P",
        population: 11597,
        countryCode: "HR",
        name: "Križevci",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "06",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Koprivničko-Križevačka",
        lat: "46.02194",
        fcode: "PPLA2",
      },
      {
        adminCode1: "04",
        lng: "13.52389",
        geonameId: 3188498,
        toponymName: "Umag",
        countryId: "3202326",
        fcl: "P",
        population: 7807,
        countryCode: "HR",
        name: "Umag",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "18",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Istarska",
        lat: "45.43139",
        fcode: "PPLA2",
      },
      {
        adminCode1: "08",
        lng: "14.90583",
        geonameId: 3191055,
        toponymName: "Senj",
        countryId: "3202326",
        fcl: "P",
        population: 5518,
        countryCode: "HR",
        name: "Senj",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "09",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Ličko-Senjska",
        lat: "44.98944",
        fcode: "PPLA2",
      },
      {
        adminCode1: "17",
        lng: "17.70278",
        geonameId: 3192932,
        toponymName: "Slatina",
        countryId: "3202326",
        fcl: "P",
        population: 10973,
        countryCode: "HR",
        name: "Slatina",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "10",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Virovitičko-Podravska",
        lat: "45.70333",
        fcode: "PPLA2",
      },
      {
        adminCode1: "12",
        lng: "14.30782",
        geonameId: 3194099,
        toponymName: "Opatija",
        countryId: "3202326",
        fcl: "P",
        population: 7888,
        countryCode: "HR",
        name: "Opatija",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "08",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Primorsko-Goranska",
        lat: "45.33658",
        fcode: "PPLA2",
      },
      {
        adminCode1: "12",
        lng: "14.78889",
        geonameId: 3194355,
        toponymName: "Novi Vinodolski",
        countryId: "3202326",
        fcl: "P",
        population: 5282,
        countryCode: "HR",
        name: "Novi Vinodolski",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "08",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Primorsko-Goranska",
        lat: "45.12806",
        fcode: "PPLA2",
      },
      {
        adminCode1: "18",
        lng: "18.6975",
        geonameId: 3186294,
        toponymName: "Županja",
        countryId: "3202326",
        fcl: "P",
        population: 13842,
        countryCode: "HR",
        name: "Županja",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "16",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Vukovarsko-Srijemska",
        lat: "45.0775",
        fcode: "PPLA2",
      },
      {
        adminCode1: "12",
        lng: "14.69278",
        geonameId: 3202507,
        toponymName: "Crikvenica",
        countryId: "3202326",
        fcl: "P",
        population: 7156,
        countryCode: "HR",
        name: "Crikvenica",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "08",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Primorsko-Goranska",
        lat: "45.17722",
        fcode: "PPLA2",
      },
      {
        adminCode1: "19",
        lng: "15.45194",
        geonameId: 3204121,
        toponymName: "Biograd na Moru",
        countryId: "3202326",
        fcl: "P",
        population: 5285,
        countryCode: "HR",
        name: "Biograd na Moru",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "13",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Zadarska",
        lat: "43.94333",
        fcode: "PPLA2",
      },
      {
        adminCode1: "10",
        lng: "18.60361",
        geonameId: 3204320,
        toponymName: "Beli Manastir",
        countryId: "3202326",
        fcl: "P",
        population: 8713,
        countryCode: "HR",
        name: "Beli Manastir",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "14",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Osječko-Baranjska",
        lat: "45.77",
        fcode: "PPLA2",
      },
      {
        adminCode1: "21",
        lng: "15.88245",
        geonameId: 3209380,
        toponymName: "Stenjevec",
        countryId: "3202326",
        fcl: "P",
        population: 41257,
        countryCode: "HR",
        name: "Stenjevec",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "21",
        },
        countryName: "Hrvatska",
        fcodeName: "populated place",
        adminName1: "Grad Zagreb",
        lat: "45.80846",
        fcode: "PPL",
      },
      {
        adminCode1: "16",
        lng: "16.12",
        geonameId: 3199076,
        toponymName: "Ivanec",
        countryId: "3202326",
        fcl: "P",
        population: 5461,
        countryCode: "HR",
        name: "Ivanec",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "05",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Varaždinska",
        lat: "46.22306",
        fcode: "PPLA2",
      },
      {
        adminCode1: "18",
        lng: "19.37694",
        geonameId: 3199128,
        toponymName: "Ilok",
        countryId: "3202326",
        fcl: "P",
        population: 5926,
        countryCode: "HR",
        name: "Ilok",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "16",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Vukovarsko-Srijemska",
        lat: "45.22222",
        fcode: "PPLA2",
      },
      {
        adminCode1: "06",
        lng: "17.06972",
        geonameId: 3200961,
        toponymName: "Đurđevac",
        countryId: "3202326",
        fcl: "P",
        population: 6349,
        countryCode: "HR",
        name: "Đurđevac",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "06",
        },
        countryName: "Hrvatska",
        fcodeName: "populated place",
        adminName1: "Koprivničko-Križevačka",
        lat: "46.04111",
        fcode: "PPL",
      },
      {
        adminCode1: "04",
        lng: "14.11972",
        geonameId: 3196834,
        toponymName: "Labin",
        countryId: "3202326",
        fcl: "P",
        population: 7943,
        countryCode: "HR",
        name: "Labin",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "18",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Istarska",
        lat: "45.095",
        fcode: "PPLA2",
      },
      {
        adminCode1: "10",
        lng: "18.41861",
        geonameId: 3188395,
        toponymName: "Valpovo",
        countryId: "3202326",
        fcl: "P",
        population: 7943,
        countryCode: "HR",
        name: "Valpovo",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "14",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Osječko-Baranjska",
        lat: "45.66083",
        fcode: "PPLA2",
      },
      {
        adminCode1: "20",
        lng: "15.71806",
        geonameId: 3191316,
        toponymName: "Samobor",
        countryId: "3202326",
        fcl: "P",
        population: 15221,
        countryCode: "HR",
        name: "Samobor",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "01",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Zagrebačka",
        lat: "45.80306",
        fcode: "PPLA2",
      },
      {
        adminCode1: "15",
        lng: "16.68861",
        geonameId: 3194114,
        toponymName: "Omiš",
        countryId: "3202326",
        fcl: "P",
        population: 6597,
        countryCode: "HR",
        name: "Omiš",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "17",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Splitsko-Dalmatinska",
        lat: "43.44472",
        fcode: "PPLA2",
      },
      {
        adminCode1: "05",
        lng: "15.22861",
        geonameId: 3194183,
        toponymName: "Ogulin",
        countryId: "3202326",
        fcl: "P",
        population: 8755,
        countryCode: "HR",
        name: "Ogulin",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "04",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Karlovačka",
        lat: "45.26611",
        fcode: "PPLA2",
      },
      {
        adminCode1: "02",
        lng: "17.38306",
        geonameId: 3194449,
        toponymName: "Nova Gradiška",
        countryId: "3202326",
        fcl: "P",
        population: 13329,
        countryCode: "HR",
        name: "Nova Gradiška",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "12",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Brodsko-Posavska",
        lat: "45.255",
        fcode: "PPLA2",
      },
      {
        adminCode1: "10",
        lng: "18.08778",
        geonameId: 3194581,
        toponymName: "Našice",
        countryId: "3202326",
        fcl: "P",
        population: 8213,
        countryCode: "HR",
        name: "Našice",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "14",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Osječko-Baranjska",
        lat: "45.48861",
        fcode: "PPLA2",
      },
      {
        adminCode1: "01",
        lng: "17.225",
        geonameId: 3202184,
        toponymName: "Daruvar",
        countryId: "3202326",
        fcl: "P",
        population: 9863,
        countryCode: "HR",
        name: "Daruvar",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "07",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Bjelovarsko-Bilogorska",
        lat: "45.59056",
        fcode: "PPLA2",
      },
      {
        adminCode1: "04",
        lng: "13.96667",
        geonameId: 3202942,
        toponymName: "Buzet",
        countryId: "3202326",
        fcl: "P",
        population: 6059,
        countryCode: "HR",
        name: "Buzet",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "18",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Istarska",
        lat: "45.40944",
        fcode: "PPLA2",
      },
      {
        adminCode1: "21",
        lng: "15.91069",
        geonameId: 3203344,
        toponymName: "Brezovica",
        countryId: "3202326",
        fcl: "P",
        population: 10884,
        countryCode: "HR",
        name: "Brezovica",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "21",
        },
        countryName: "Hrvatska",
        fcodeName: "populated place",
        adminName1: "Grad Zagreb",
        lat: "45.72919",
        fcode: "PPL",
      },
      {
        adminCode1: "10",
        lng: "18.40583",
        geonameId: 3204317,
        toponymName: "Belišće",
        countryId: "3202326",
        fcl: "P",
        population: 7232,
        countryCode: "HR",
        name: "Belišće",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "14",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Osječko-Baranjska",
        lat: "45.68028",
        fcode: "PPLA2",
      },
      {
        adminCode1: "21",
        lng: "15.97753",
        geonameId: 6618983,
        toponymName: "Centar",
        countryId: "3202326",
        fcl: "P",
        population: 37000,
        countryCode: "HR",
        name: "Centar",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "21",
        },
        countryName: "Hrvatska",
        fcodeName: "section of populated place",
        adminName1: "Grad Zagreb",
        lat: "45.81313",
        fcode: "PPLX",
      },
      {
        adminCode1: "10",
        lng: "18.74722",
        geonameId: 3189161,
        toponymName: "Tenja",
        countryId: "3202326",
        fcl: "P",
        population: 7376,
        countryCode: "HR",
        name: "Tenja",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "14",
        },
        countryName: "Hrvatska",
        fcodeName: "populated place",
        adminName1: "Osječko-Baranjska",
        lat: "45.49806",
        fcode: "PPL",
      },
      {
        adminCode1: "14",
        lng: "16.625",
        geonameId: 3192724,
        toponymName: "Popovača",
        countryId: "3202326",
        fcl: "P",
        population: 12000,
        countryCode: "HR",
        name: "Popovača",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "03",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Sisačko-Moslavačka",
        lat: "45.56972",
        fcode: "PPLA2",
      },
      {
        adminCode1: "14",
        lng: "16.29",
        geonameId: 3193420,
        toponymName: "Petrinja",
        countryId: "3202326",
        fcl: "P",
        population: 13868,
        countryCode: "HR",
        name: "Petrinja",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "03",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Sisačko-Moslavačka",
        lat: "45.4375",
        fcode: "PPLA2",
      },
      {
        adminCode1: "09",
        lng: "16.44111",
        geonameId: 3194626,
        toponymName: "Mursko Središće",
        countryId: "3202326",
        fcl: "P",
        population: 6307,
        countryCode: "HR",
        name: "Mursko Središće",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "20",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Međimurska",
        lat: "46.50944",
        fcode: "PPLA2",
      },
      {
        adminCode1: "13",
        lng: "15.78278",
        geonameId: 3187489,
        toponymName: "Vodice",
        countryId: "3202326",
        fcl: "P",
        population: 6146,
        countryCode: "HR",
        name: "Vodice",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "15",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Šibensko-Kninska",
        lat: "43.76083",
        fcode: "PPLA2",
      },
      {
        adminCode1: "10",
        lng: "18.61389",
        geonameId: 3187657,
        toponymName: "Višnjevac",
        countryId: "3202326",
        fcl: "P",
        population: 6680,
        countryCode: "HR",
        name: "Višnjevac",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "14",
        },
        countryName: "Hrvatska",
        fcodeName: "populated place",
        adminName1: "Osječko-Baranjska",
        lat: "45.56861",
        fcode: "PPL",
      },
      {
        adminCode1: "18",
        lng: "18.96694",
        geonameId: 3203670,
        toponymName: "Borovo",
        countryId: "3202326",
        fcl: "P",
        population: 5056,
        countryCode: "HR",
        name: "Borovo",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "16",
        },
        countryName: "Hrvatska",
        fcodeName: "populated place",
        adminName1: "Vukovarsko-Srijemska",
        lat: "45.37639",
        fcode: "PPL",
      },
      {
        adminCode1: "15",
        lng: "16.35",
        geonameId: 3198212,
        toponymName: "Kaštel Stari",
        countryId: "3202326",
        fcl: "P",
        population: 7052,
        countryCode: "HR",
        name: "Kaštel Stari",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "17",
        },
        countryName: "Hrvatska",
        fcodeName: "populated place",
        adminName1: "Splitsko-Dalmatinska",
        lat: "43.55",
        fcode: "PPL",
      },
      {
        adminCode1: "15",
        lng: "16.33333",
        geonameId: 3198214,
        toponymName: "Kaštel Novi",
        countryId: "3202326",
        fcl: "P",
        population: 6411,
        countryCode: "HR",
        name: "Kaštel Novi",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "17",
        },
        countryName: "Hrvatska",
        fcodeName: "populated place",
        adminName1: "Splitsko-Dalmatinska",
        lat: "43.55",
        fcode: "PPL",
      },
      {
        adminCode1: "15",
        lng: "16.3675",
        geonameId: 3198215,
        toponymName: "Kaštel Lukšić",
        countryId: "3202326",
        fcl: "P",
        population: 5425,
        countryCode: "HR",
        name: "Kaštel Lukšić",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "17",
        },
        countryName: "Hrvatska",
        fcodeName: "populated place",
        adminName1: "Splitsko-Dalmatinska",
        lat: "43.55528",
        fcode: "PPL",
      },
      {
        adminCode1: "15",
        lng: "16.38333",
        geonameId: 3198216,
        toponymName: "Kaštel Kambelovac",
        countryId: "3202326",
        fcl: "P",
        population: 5027,
        countryCode: "HR",
        name: "Kaštel Kambelovac",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "17",
        },
        countryName: "Hrvatska",
        fcodeName: "populated place",
        adminName1: "Splitsko-Dalmatinska",
        lat: "43.55",
        fcode: "PPL",
      },
      {
        adminCode1: "12",
        lng: "14.43028",
        geonameId: 3201217,
        toponymName: "Drenova",
        countryId: "3202326",
        fcl: "P",
        population: 7638,
        countryCode: "HR",
        name: "Drenova",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "08",
        },
        countryName: "Hrvatska",
        fcodeName: "populated place",
        adminName1: "Primorsko-Goranska",
        lat: "45.35",
        fcode: "PPL",
      },
      {
        adminCode1: "18",
        lng: "18.68389",
        geonameId: 3199051,
        toponymName: "Ivankovo",
        countryId: "3202326",
        fcl: "P",
        population: 6728,
        countryCode: "HR",
        name: "Ivankovo",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "16",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Vukovarsko-Srijemska",
        lat: "45.28861",
        fcode: "PPLA2",
      },
      {
        adminCode1: "18",
        lng: "18.85333",
        geonameId: 3199473,
        toponymName: "Gunja",
        countryId: "3202326",
        fcl: "P",
        population: 5058,
        countryCode: "HR",
        name: "Gunja",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "16",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Vukovarsko-Srijemska",
        lat: "44.88",
        fcode: "PPLA2",
      },
      {
        adminCode1: "17",
        lng: "17.22944",
        geonameId: 3193305,
        toponymName: "Pitomača",
        countryId: "3202326",
        fcl: "P",
        population: 5740,
        countryCode: "HR",
        name: "Pitomača",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "10",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Virovitičko-Podravska",
        lat: "45.95056",
        fcode: "PPLA2",
      },
      {
        adminCode1: "18",
        lng: "18.88389",
        geonameId: 3193781,
        toponymName: "Otok",
        countryId: "3202326",
        fcl: "P",
        population: 5887,
        countryCode: "HR",
        name: "Otok",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "16",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Vukovarsko-Srijemska",
        lat: "45.14667",
        fcode: "PPLA2",
      },
      {
        adminCode1: "14",
        lng: "16.97694",
        geonameId: 3194319,
        toponymName: "Novska",
        countryId: "3202326",
        fcl: "P",
        population: 7306,
        countryCode: "HR",
        name: "Novska",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "03",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Sisačko-Moslavačka",
        lat: "45.34056",
        fcode: "PPLA2",
      },
      {
        adminCode1: "10",
        lng: "18.69972",
        geonameId: 3202186,
        toponymName: "Darda",
        countryId: "3202326",
        fcl: "P",
        population: 5420,
        countryCode: "HR",
        name: "Darda",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "14",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Osječko-Baranjska",
        lat: "45.62806",
        fcode: "PPLA2",
      },
      {
        adminCode1: "10",
        lng: "18.56333",
        geonameId: 3202743,
        toponymName: "Čepin",
        countryId: "3202326",
        fcl: "P",
        population: 9548,
        countryCode: "HR",
        name: "Čepin",
        fclName: "city, village,...",
        adminCodes1: {
          ISO3166_2: "14",
        },
        countryName: "Hrvatska",
        fcodeName: "seat of a second-order administrative division",
        adminName1: "Osječko-Baranjska",
        lat: "45.52361",
        fcode: "PPLA2",
      },
    ],
  },
  "Response payload": {
    EDITOR_CONFIG: {
      text: '{"totalResultsCount":82,"geonames":[{"adminCode1":"21","lng":"15.97798","geonameId":3186886,"toponymName":"Zagreb","countryId":"3202326","fcl":"P","population":698966,"countryCode":"HR","name":"Zagreb","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"21"},"countryName":"Hrvatska","fcodeName":"capital of a political entity","adminName1":"Grad Zagreb","lat":"45.81444","fcode":"PPLC"},{"adminCode1":"15","lng":"16.43915","geonameId":3190261,"toponymName":"Split","countryId":"3202326","fcl":"P","population":176314,"countryCode":"HR","name":"Split","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"17"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Splitsko-Dalmatinska","lat":"43.50891","fcode":"PPLA"},{"adminCode1":"12","lng":"14.44241","geonameId":3191648,"toponymName":"Rijeka","countryId":"3202326","fcl":"P","population":141172,"countryCode":"HR","name":"Rijeka","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"08"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Primorsko-Goranska","lat":"45.32673","fcode":"PPLA"},{"adminCode1":"10","lng":"18.69389","geonameId":3193935,"toponymName":"Osijek","countryId":"3202326","fcl":"P","population":88140,"countryCode":"HR","name":"Osijek","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"14"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Osječko-Baranjska","lat":"45.55111","fcode":"PPLA"},{"adminCode1":"02","lng":"18.01556","geonameId":3190586,"toponymName":"Slavonski Brod","countryId":"3202326","fcl":"P","population":60742,"countryCode":"HR","name":"Slavonski Brod","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"12"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Brodsko-Posavska","lat":"45.16028","fcode":"PPLA"},{"adminCode1":"19","lng":"15.22514","geonameId":3186952,"toponymName":"Zadar","countryId":"3202326","fcl":"P","population":71258,"countryCode":"HR","name":"Zadar","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"13"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Zadarska","lat":"44.11578","fcode":"PPLA"},{"adminCode1":"05","lng":"15.55","geonameId":3345300,"toponymName":"Karlovac","countryId":"3202326","fcl":"P","population":46833,"countryCode":"HR","name":"Karlovac","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"04"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Karlovačka","lat":"45.49167","fcode":"PPLA"},{"adminCode1":"16","lng":"16.33778","geonameId":3188383,"toponymName":"Varaždin","countryId":"3202326","fcl":"P","population":41808,"countryCode":"HR","name":"Varaždin","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"05"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Varaždinska","lat":"46.30444","fcode":"PPLA"},{"adminCode1":"04","lng":"13.84806","geonameId":3192224,"toponymName":"Pula","countryId":"3202326","fcl":"P","population":59078,"countryCode":"HR","name":"Pula","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"18"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Istarska","lat":"44.86833","fcode":"PPLA2"},{"adminCode1":"21","lng":"16.11639","geonameId":3190966,"toponymName":"Sesvete","countryId":"3202326","fcl":"P","population":52411,"countryCode":"HR","name":"Sesvete","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"21"},"countryName":"Hrvatska","fcodeName":"populated place","adminName1":"Grad Zagreb","lat":"45.83111","fcode":"PPL"},{"adminCode1":"03","lng":"18.10909","geonameId":3201047,"toponymName":"Dubrovnik","countryId":"3202326","fcl":"P","population":28428,"countryCode":"HR","name":"Dubrovnik","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"19"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Dubrovačko-Neretvanska","lat":"42.64125","fcode":"PPLA"},{"adminCode1":"06","lng":"16.8275","geonameId":3197728,"toponymName":"Koprivnica","countryId":"3202326","fcl":"P","population":25579,"countryCode":"HR","name":"Koprivnica","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"06"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Koprivničko-Križevačka","lat":"46.16278","fcode":"PPLA"},{"adminCode1":"11","lng":"17.68528","geonameId":3190589,"toponymName":"Požega","countryId":"3202326","fcl":"P","population":21153,"countryCode":"HR","name":"Požega","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"11"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Požeško-Slavonska","lat":"45.34028","fcode":"PPLA"},{"adminCode1":"14","lng":"16.37833","geonameId":3190813,"toponymName":"Sisak","countryId":"3202326","fcl":"P","population":35748,"countryCode":"HR","name":"Sisak","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"03"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Sisačko-Moslavačka","lat":"45.46611","fcode":"PPLA"},{"adminCode1":"13","lng":"15.8942","geonameId":3190941,"toponymName":"Šibenik","countryId":"3202326","fcl":"P","population":37112,"countryCode":"HR","name":"Šibenik","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"15"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Šibensko-Kninska","lat":"43.73429","fcode":"PPLA"},{"adminCode1":"18","lng":"19.00225","geonameId":3187047,"toponymName":"Vukovar","countryId":"3202326","fcl":"P","population":29584,"countryCode":"HR","name":"Vukovar","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"16"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Vukovarsko-Srijemska","lat":"45.35161","fcode":"PPLA"},{"adminCode1":"09","lng":"16.43389","geonameId":3202888,"toponymName":"Čakovec","countryId":"3202326","fcl":"P","population":15867,"countryCode":"HR","name":"Čakovec","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"20"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Međimurska","lat":"46.38444","fcode":"PPLA"},{"adminCode1":"01","lng":"16.84889","geonameId":3203982,"toponymName":"Bjelovar","countryId":"3202326","fcl":"P","population":28275,"countryCode":"HR","name":"Bjelovar","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"07"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Bjelovarsko-Bilogorska","lat":"45.89861","fcode":"PPLA"},{"adminCode1":"04","lng":"13.93667","geonameId":3193561,"toponymName":"Pazin","countryId":"3202326","fcl":"P","population":5010,"countryCode":"HR","name":"Pazin","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"18"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Istarska","lat":"45.24028","fcode":"PPLA"},{"adminCode1":"08","lng":"15.37472","geonameId":3199873,"toponymName":"Gospić","countryId":"3202326","fcl":"P","population":6118,"countryCode":"HR","name":"Gospić","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"09"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Ličko-Senjska","lat":"44.54611","fcode":"PPLA"},{"adminCode1":"15","lng":"16.49314","geonameId":3190359,"toponymName":"Solin","countryId":"3202326","fcl":"P","population":20212,"countryCode":"HR","name":"Solin","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"17"},"countryName":"Hrvatska","fcodeName":"populated place","adminName1":"Splitsko-Dalmatinska","lat":"43.5432","fcode":"PPL"},{"adminCode1":"17","lng":"17.38389","geonameId":3187694,"toponymName":"Virovitica","countryId":"3202326","fcl":"P","population":15665,"countryCode":"HR","name":"Virovitica","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"10"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Virovitičko-Podravska","lat":"45.83194","fcode":"PPLA"},{"adminCode1":"07","lng":"15.87889","geonameId":3197369,"toponymName":"Krapina","countryId":"3202326","fcl":"P","population":4725,"countryCode":"HR","name":"Krapina","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"02"},"countryName":"Hrvatska","fcodeName":"seat of a first-order administrative division","adminName1":"Krapinsko-Zagorska","lat":"46.16083","fcode":"PPLA"},{"adminCode1":"15","lng":"16.25167","geonameId":3188763,"toponymName":"Trogir","countryId":"3202326","fcl":"P","population":10960,"countryCode":"HR","name":"Trogir","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"17"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Splitsko-Dalmatinska","lat":"43.5125","fcode":"PPLA2"},{"adminCode1":"04","lng":"13.63457","geonameId":3191518,"toponymName":"Rovinj","countryId":"3202326","fcl":"P","population":13533,"countryCode":"HR","name":"Rovinj","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"18"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Istarska","lat":"45.08268","fcode":"PPLA2"},{"adminCode1":"03","lng":"17.64833","geonameId":3195222,"toponymName":"Metković","countryId":"3202326","fcl":"P","population":13941,"countryCode":"HR","name":"Metković","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"19"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Dubrovačko-Neretvanska","lat":"43.05417","fcode":"PPLA2"},{"adminCode1":"15","lng":"17.01778","geonameId":3195890,"toponymName":"Makarska","countryId":"3202326","fcl":"P","population":13446,"countryCode":"HR","name":"Makarska","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"17"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Splitsko-Dalmatinska","lat":"43.29694","fcode":"PPLA2"},{"adminCode1":"13","lng":"16.19662","geonameId":3197986,"toponymName":"Knin","countryId":"3202326","fcl":"P","population":11182,"countryCode":"HR","name":"Knin","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"15"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Šibensko-Kninska","lat":"44.04063","fcode":"PPLA2"},{"adminCode1":"20","lng":"16.07556","geonameId":3188244,"toponymName":"Velika Gorica","countryId":"3202326","fcl":"P","population":35072,"countryCode":"HR","name":"Velika Gorica","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"01"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Zagrebačka","lat":"45.7125","fcode":"PPLA2"},{"adminCode1":"15","lng":"16.63944","geonameId":3190865,"toponymName":"Sinj","countryId":"3202326","fcl":"P","population":11524,"countryCode":"HR","name":"Sinj","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"17"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Splitsko-Dalmatinska","lat":"43.70361","fcode":"PPLA2"},{"adminCode1":"04","lng":"13.59511","geonameId":3192699,"toponymName":"Poreč","countryId":"3202326","fcl":"P","population":10499,"countryCode":"HR","name":"Poreč","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"18"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Istarska","lat":"45.22567","fcode":"PPLA2"},{"adminCode1":"15","lng":"16.55013","geonameId":3192910,"toponymName":"Podstrana","countryId":"3202326","fcl":"P","population":9129,"countryCode":"HR","name":"Podstrana","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"17"},"countryName":"Hrvatska","fcodeName":"populated place","adminName1":"Splitsko-Dalmatinska","lat":"43.48668","fcode":"PPL"},{"adminCode1":"20","lng":"15.80778","geonameId":3186781,"toponymName":"Zaprešić","countryId":"3202326","fcl":"P","population":19664,"countryCode":"HR","name":"Zaprešić","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"01"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Zagrebačka","lat":"45.85639","fcode":"PPLA2"},{"adminCode1":"18","lng":"18.80472","geonameId":3187719,"toponymName":"Vinkovci","countryId":"3202326","fcl":"P","population":33314,"countryCode":"HR","name":"Vinkovci","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"16"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Vukovarsko-Srijemska","lat":"45.28833","fcode":"PPLA2"},{"adminCode1":"10","lng":"18.41056","geonameId":3202220,"toponymName":"Đakovo","countryId":"3202326","fcl":"P","population":19491,"countryCode":"HR","name":"Đakovo","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"14"},"countryName":"Hrvatska","fcodeName":"populated place","adminName1":"Osječko-Baranjska","lat":"45.30833","fcode":"PPL"},{"adminCode1":"20","lng":"15.64861","geonameId":3198799,"toponymName":"Jastrebarsko","countryId":"3202326","fcl":"P","population":5445,"countryCode":"HR","name":"Jastrebarsko","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"01"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Zagrebačka","lat":"45.66833","fcode":"PPLA2"},{"adminCode1":"14","lng":"16.78194","geonameId":3196864,"toponymName":"Kutina","countryId":"3202326","fcl":"P","population":14886,"countryCode":"HR","name":"Kutina","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"03"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Sisačko-Moslavaka","lat":"45.475","fcode":"PPLA2"},{"adminCode1":"06","lng":"16.5425","geonameId":3197230,"toponymName":"KriÅ¾evci","countryId":"3202326","fcl":"P","population":11597,"countryCode":"HR","name":"KriÅ¾evci","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"06"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"KoprivniÄko-KriÅ¾evaÄka","lat":"46.02194","fcode":"PPLA2"},{"adminCode1":"04","lng":"13.52389","geonameId":3188498,"toponymName":"Umag","countryId":"3202326","fcl":"P","population":7807,"countryCode":"HR","name":"Umag","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"18"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Istarska","lat":"45.43139","fcode":"PPLA2"},{"adminCode1":"08","lng":"14.90583","geonameId":3191055,"toponymName":"Senj","countryId":"3202326","fcl":"P","population":5518,"countryCode":"HR","name":"Senj","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"09"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"LiÄko-Senjska","lat":"44.98944","fcode":"PPLA2"},{"adminCode1":"17","lng":"17.70278","geonameId":3192932,"toponymName":"Slatina","countryId":"3202326","fcl":"P","population":10973,"countryCode":"HR","name":"Slatina","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"10"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Virovitičko-Podravska","lat":"45.70333","fcode":"PPLA2"},{"adminCode1":"12","lng":"14.30782","geonameId":3194099,"toponymName":"Opatija","countryId":"3202326","fcl":"P","population":7888,"countryCode":"HR","name":"Opatija","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"08"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Primorsko-Goranska","lat":"45.33658","fcode":"PPLA2"},{"adminCode1":"12","lng":"14.78889","geonameId":3194355,"toponymName":"Novi Vinodolski","countryId":"3202326","fcl":"P","population":5282,"countryCode":"HR","name":"Novi Vinodolski","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"08"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Primorsko-Goranska","lat":"45.12806","fcode":"PPLA2"},{"adminCode1":"18","lng":"18.6975","geonameId":3186294,"toponymName":"Županja","countryId":"3202326","fcl":"P","population":13842,"countryCode":"HR","name":"Županja","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"16"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Vukovarsko-Srijemska","lat":"45.0775","fcode":"PPLA2"},{"adminCode1":"12","lng":"14.69278","geonameId":3202507,"toponymName":"Crikvenica","countryId":"3202326","fcl":"P","population":7156,"countryCode":"HR","name":"Crikvenica","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"08"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Primorsko-Goranska","lat":"45.17722","fcode":"PPLA2"},{"adminCode1":"19","lng":"15.45194","geonameId":3204121,"toponymName":"Biograd na Moru","countryId":"3202326","fcl":"P","population":5285,"countryCode":"HR","name":"Biograd na Moru","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"13"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Zadarska","lat":"43.94333","fcode":"PPLA2"},{"adminCode1":"10","lng":"18.60361","geonameId":3204320,"toponymName":"Beli Manastir","countryId":"3202326","fcl":"P","population":8713,"countryCode":"HR","name":"Beli Manastir","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"14"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Osječko-Baranjska","lat":"45.77","fcode":"PPLA2"},{"adminCode1":"21","lng":"15.88245","geonameId":3209380,"toponymName":"Stenjevec","countryId":"3202326","fcl":"P","population":41257,"countryCode":"HR","name":"Stenjevec","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"21"},"countryName":"Hrvatska","fcodeName":"populated place","adminName1":"Grad Zagreb","lat":"45.80846","fcode":"PPL"},{"adminCode1":"16","lng":"16.12","geonameId":3199076,"toponymName":"Ivanec","countryId":"3202326","fcl":"P","population":5461,"countryCode":"HR","name":"Ivanec","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"05"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Varaždinska","lat":"46.22306","fcode":"PPLA2"},{"adminCode1":"18","lng":"19.37694","geonameId":3199128,"toponymName":"Ilok","countryId":"3202326","fcl":"P","population":5926,"countryCode":"HR","name":"Ilok","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"16"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Vukovarsko-Srijemska","lat":"45.22222","fcode":"PPLA2"},{"adminCode1":"06","lng":"17.06972","geonameId":3200961,"toponymName":"Đurđevac","countryId":"3202326","fcl":"P","population":6349,"countryCode":"HR","name":"Đurđevac","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"06"},"countryName":"Hrvatska","fcodeName":"populated place","adminName1":"Koprivničko-Križevačka","lat":"46.04111","fcode":"PPL"},{"adminCode1":"04","lng":"14.11972","geonameId":3196834,"toponymName":"Labin","countryId":"3202326","fcl":"P","population":7943,"countryCode":"HR","name":"Labin","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"18"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Istarska","lat":"45.095","fcode":"PPLA2"},{"adminCode1":"10","lng":"18.41861","geonameId":3188395,"toponymName":"Valpovo","countryId":"3202326","fcl":"P","population":7943,"countryCode":"HR","name":"Valpovo","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"14"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Osječko-Baranjska","lat":"45.66083","fcode":"PPLA2"},{"adminCode1":"20","lng":"15.71806","geonameId":3191316,"toponymName":"Samobor","countryId":"3202326","fcl":"P","population":15221,"countryCode":"HR","name":"Samobor","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"01"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Zagrebačka","lat":"45.80306","fcode":"PPLA2"},{"adminCode1":"15","lng":"16.68861","geonameId":3194114,"toponymName":"Omiš","countryId":"3202326","fcl":"P","population":6597,"countryCode":"HR","name":"Omiš","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"17"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Splitsko-Dalmatinska","lat":"43.44472","fcode":"PPLA2"},{"adminCode1":"05","lng":"15.22861","geonameId":3194183,"toponymName":"Ogulin","countryId":"3202326","fcl":"P","population":8755,"countryCode":"HR","name":"Ogulin","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"04"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Karlovačka","lat":"45.26611","fcode":"PPLA2"},{"adminCode1":"02","lng":"17.38306","geonameId":3194449,"toponymName":"Nova Gradiška","countryId":"3202326","fcl":"P","population":13329,"countryCode":"HR","name":"Nova Gradiška","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"12"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Brodsko-Posavska","lat":"45.255","fcode":"PPLA2"},{"adminCode1":"10","lng":"18.08778","geonameId":3194581,"toponymName":"Našice","countryId":"3202326","fcl":"P","population":8213,"countryCode":"HR","name":"Našice","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"14"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Osječko-Baranjska","lat":"45.48861","fcode":"PPLA2"},{"adminCode1":"01","lng":"17.225","geonameId":3202184,"toponymName":"Daruvar","countryId":"3202326","fcl":"P","population":9863,"countryCode":"HR","name":"Daruvar","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"07"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Bjelovarsko-Bilogorska","lat":"45.59056","fcode":"PPLA2"},{"adminCode1":"04","lng":"13.96667","geonameId":3202942,"toponymName":"Buzet","countryId":"3202326","fcl":"P","population":6059,"countryCode":"HR","name":"Buzet","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"18"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Istarska","lat":"45.40944","fcode":"PPLA2"},{"adminCode1":"21","lng":"15.91069","geonameId":3203344,"toponymName":"Brezovica","countryId":"3202326","fcl":"P","population":10884,"countryCode":"HR","name":"Brezovica","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"21"},"countryName":"Hrvatska","fcodeName":"populated place","adminName1":"Grad Zagreb","lat":"45.72919","fcode":"PPL"},{"adminCode1":"10","lng":"18.40583","geonameId":3204317,"toponymName":"Belišće","countryId":"3202326","fcl":"P","population":7232,"countryCode":"HR","name":"Belišće","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"14"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Osječko-Baranjska","lat":"45.68028","fcode":"PPLA2"},{"adminCode1":"21","lng":"15.97753","geonameId":6618983,"toponymName":"Centar","countryId":"3202326","fcl":"P","population":37000,"countryCode":"HR","name":"Centar","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"21"},"countryName":"Hrvatska","fcodeName":"section of populated place","adminName1":"Grad Zagreb","lat":"45.81313","fcode":"PPLX"},{"adminCode1":"10","lng":"18.74722","geonameId":3189161,"toponymName":"Tenja","countryId":"3202326","fcl":"P","population":7376,"countryCode":"HR","name":"Tenja","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"14"},"countryName":"Hrvatska","fcodeName":"populated place","adminName1":"Osječko-Baranjska","lat":"45.49806","fcode":"PPL"},{"adminCode1":"14","lng":"16.625","geonameId":3192724,"toponymName":"Popovača","countryId":"3202326","fcl":"P","population":12000,"countryCode":"HR","name":"Popovača","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"03"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Sisačko-Moslavačka","lat":"45.56972","fcode":"PPLA2"},{"adminCode1":"14","lng":"16.29","geonameId":3193420,"toponymName":"Petrinja","countryId":"3202326","fcl":"P","population":13868,"countryCode":"HR","name":"Petrinja","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"03"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Sisačko-Moslavačka","lat":"45.4375","fcode":"PPLA2"},{"adminCode1":"09","lng":"16.44111","geonameId":3194626,"toponymName":"Mursko Središće","countryId":"3202326","fcl":"P","population":6307,"countryCode":"HR","name":"Mursko Središće","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"20"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Međimurska","lat":"46.50944","fcode":"PPLA2"},{"adminCode1":"13","lng":"15.78278","geonameId":3187489,"toponymName":"Vodice","countryId":"3202326","fcl":"P","population":6146,"countryCode":"HR","name":"Vodice","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"15"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Šibensko-Kninska","lat":"43.76083","fcode":"PPLA2"},{"adminCode1":"10","lng":"18.61389","geonameId":3187657,"toponymName":"Višnjevac","countryId":"3202326","fcl":"P","population":6680,"countryCode":"HR","name":"Višnjevac","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"14"},"countryName":"Hrvatska","fcodeName":"populated place","adminName1":"Osječko-Baranjska","lat":"45.56861","fcode":"PPL"},{"adminCode1":"18","lng":"18.96694","geonameId":3203670,"toponymName":"Borovo","countryId":"3202326","fcl":"P","population":5056,"countryCode":"HR","name":"Borovo","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"16"},"countryName":"Hrvatska","fcodeName":"populated place","adminName1":"Vukovarsko-Srijemska","lat":"45.37639","fcode":"PPL"},{"adminCode1":"15","lng":"16.35","geonameId":3198212,"toponymName":"Kaštel Stari","countryId":"3202326","fcl":"P","population":7052,"countryCode":"HR","name":"Kaštel Stari","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"17"},"countryName":"Hrvatska","fcodeName":"populated place","adminName1":"Splitsko-Dalmatinska","lat":"43.55","fcode":"PPL"},{"adminCode1":"15","lng":"16.33333","geonameId":3198214,"toponymName":"Kaštel Novi","countryId":"3202326","fcl":"P","population":6411,"countryCode":"HR","name":"Kaštel Novi","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"17"},"countryName":"Hrvatska","fcodeName":"populated place","adminName1":"Splitsko-Dalmatinska","lat":"43.55","fcode":"PPL"},{"adminCode1":"15","lng":"16.3675","geonameId":3198215,"toponymName":"Kaštel Lukšić","countryId":"3202326","fcl":"P","population":5425,"countryCode":"HR","name":"Kaštel Lukšić","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"17"},"countryName":"Hrvatska","fcodeName":"populated place","adminName1":"Splitsko-Dalmatinska","lat":"43.55528","fcode":"PPL"},{"adminCode1":"15","lng":"16.38333","geonameId":3198216,"toponymName":"Kaštel Kambelovac","countryId":"3202326","fcl":"P","population":5027,"countryCode":"HR","name":"Kaštel Kambelovac","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"17"},"countryName":"Hrvatska","fcodeName":"populated place","adminName1":"Splitsko-Dalmatinska","lat":"43.55","fcode":"PPL"},{"adminCode1":"12","lng":"14.43028","geonameId":3201217,"toponymName":"Drenova","countryId":"3202326","fcl":"P","population":7638,"countryCode":"HR","name":"Drenova","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"08"},"countryName":"Hrvatska","fcodeName":"populated place","adminName1":"Primorsko-Goranska","lat":"45.35","fcode":"PPL"},{"adminCode1":"18","lng":"18.68389","geonameId":3199051,"toponymName":"Ivankovo","countryId":"3202326","fcl":"P","population":6728,"countryCode":"HR","name":"Ivankovo","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"16"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Vukovarsko-Srijemska","lat":"45.28861","fcode":"PPLA2"},{"adminCode1":"18","lng":"18.85333","geonameId":3199473,"toponymName":"Gunja","countryId":"3202326","fcl":"P","population":5058,"countryCode":"HR","name":"Gunja","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"16"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Vukovarsko-Srijemska","lat":"44.88","fcode":"PPLA2"},{"adminCode1":"17","lng":"17.22944","geonameId":3193305,"toponymName":"Pitomača","countryId":"3202326","fcl":"P","population":5740,"countryCode":"HR","name":"Pitomača","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"10"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Virovitičko-Podravska","lat":"45.95056","fcode":"PPLA2"},{"adminCode1":"18","lng":"18.88389","geonameId":3193781,"toponymName":"Otok","countryId":"3202326","fcl":"P","population":5887,"countryCode":"HR","name":"Otok","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"16"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Vukovarsko-Srijemska","lat":"45.14667","fcode":"PPLA2"},{"adminCode1":"14","lng":"16.97694","geonameId":3194319,"toponymName":"Novska","countryId":"3202326","fcl":"P","population":7306,"countryCode":"HR","name":"Novska","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"03"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Sisačko-Moslavačka","lat":"45.34056","fcode":"PPLA2"},{"adminCode1":"10","lng":"18.69972","geonameId":3202186,"toponymName":"Darda","countryId":"3202326","fcl":"P","population":5420,"countryCode":"HR","name":"Darda","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"14"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Osječko-Baranjska","lat":"45.62806","fcode":"PPLA2"},{"adminCode1":"10","lng":"18.56333","geonameId":3202743,"toponymName":"Čepin","countryId":"3202326","fcl":"P","population":9548,"countryCode":"HR","name":"Čepin","fclName":"city, village,...","adminCodes1":{"ISO3166_2":"14"},"countryName":"Hrvatska","fcodeName":"seat of a second-order administrative division","adminName1":"Osječko-Baranjska","lat":"45.52361","fcode":"PPLA2"}]}',
      mode: "application/json",
    },
  },
};
